### PR TITLE
Added Development process

### PR DESCRIPTION
**Pull request by krysnuvadga**
Describes the steps to follow whenever we have to make some changes to the code or add some new features

Signed-off-by: Krys Nuvadga

### CODE REVIEW

**Comment by pombredanne** [comment]
@krysnuvadga sorry for this super late review... Is this still up to date and ready to merge?

**Comment by pombredanne** [comment]
@krysnuvadga this was missing your signed-off-by: can you at least add this to this PR as a message?

**Comment by krysnuvadga** [comment]
> @krysnuvadga sorry for this super late review... Is this still up to date and ready to merge?

Yes, very much up to date

**Comment by krysnuvadga** [comment]
> @krysnuvadga this was missing your signed-off-by: can you at least add this to this PR as a message?

Done!

**Pull request merged**
