### PR TITLE
Merge two tag-value files at the object level

### PR DESCRIPTION
**Pull request by yugeshk**
An attempt to merge two tag-value documents at the object level.
issue : https://github.com/spdx/tools-python/issues/26
Signed-off-by: Yugesh Kothari yugesh.kothari@gmail.com

### CODE REVIEW

**Comment by yugeshk** [comment]
@pombredanne I've tried to merge two tag-value files. There were quite a few areas which I feel need change - Specifically managing merging the packaging information. Currently, in line with `specification 1.2` I thought it would be more logical to adopt majority of the package information from the file that would have a newer version of `package information`. The license information however derives mostly from the **first file** provided - this I thought would befit the purpose/use-case discussed in the [issue](https://github.com/spdx/tools-python/issues/26). Would be nice if you could review/ provide more insight. The `rdf` counter-part would be simple to complete thereafter.

**Comment by yugeshk** [comment]
I could show you the results if you like - once a design gets finalized, I'll add tests as well.

**Comment by pombredanne** [comment]
Thanks for this PR! Do you mind rebasing since the base changed since?

**Comment by pombredanne** [comment]
This has gone stale so I am closing this for now. Please reopen and update if you want to complete this

**Pull request closed without merging**
