### PR TITLE
Return messages instead of modifying list #50

### PR DESCRIPTION
**Pull request by yash-nisar**
We now return messages from each `validation` function
instead of modifying lists in place.

Signed-off-by: Yash Nisar <yash.nisar@somaiya.edu>

Closes https://github.com/spdx/tools-python/issues/50

Review needed @sschuberth @pombredanne @rtgdk

### CODE REVIEW

**Comment by sschuberth** [comment]
> We now return messages from each `validation` function instead of modifying lists in place.

Ok, but *why* is that a good thing? I prefer if commit messages do not simply repeat in prose what can be seen from the diff, but explain the *rationale* behind the change.

**Comment by yash-nisar** [comment]
Sure, will add explain the rationale behind the change in a moment :) 

Thanks for your feedback.

**Comment by yash-nisar** [comment]
@sschuberth Is the commit message good enough ?

**Comment by sschuberth** [comment]
Thanks @yash-nisar, the message reads good now, but I'll leave the code comments to real Python-people like @pombredanne or @haikoschol.

**Comment by yash-nisar** [comment]
Thanks @sschuberth :)

**Comment by yash-nisar** [comment]
@pombredanne Can I have your review ? :)

**Comment by pombredanne** [comment]
@yash-nisar I would be interested to see if this breaks scancode or not before merging. There were some weird cases where the messages data passed was empty. I would assume that this would fix this. 
Yet, I would be more comfortable if you could add a few new tests that would try to tests these corner cases: what happens if `messages` is None with your updates?

**Comment by yash-nisar** [comment]
@pombredanne 
re
> what happens if messages is None with your updates?

Do you mean what would happen if our document was perfectly valid and the final `validate(...)` function returns an empty list ? Well, in that case, I've modified the tests by adding this line: 
`assert doc.validate([]) == []`. And in this case (where our document is perfectly valid), an empty list is passed to the fellow `validate(...)` functions and an empty list is returned by those functions.

**Comment by yash-nisar** [comment]
@pombredanne Any inputs ?

**Comment by yash-nisar** [comment]
@pombredanne @krysnuvadga Any inputs ?

**Comment by yash-nisar** [comment]
Note: This PR will be updated after the other open PRs get merged so please **do not merge** till then.

**Comment by pombredanne** [comment]
@yash-nisar you wrote
> Note: This PR will be updated after the other open PRs get merged so please do not merge till then. .... therefore I did not touched this

**Comment by yash-nisar** [comment]
@pombredanne Roger that.

**Comment by pombredanne** [comment]
@yash-nisar you said in a chat:

> We do return the message list which shall be empty if everything is according to our standards and shall be filled in if there are some errors

So I guess this is OK as it is now. Let me merge this then.

**Pull request merged**
