### PR TITLE
Removed check that packages have SHA1 checksum, per spec

### PR DESCRIPTION
**Pull request by njv299**
This is a simple attempt to fix this issue:

https://github.com/spdx/tools-python/issues/182

Essentially, it just removes the check for a Package checksum to be SHA1 since the SPDX spec does not require that.

### CODE REVIEW

**Review by tardyp — APPROVED** [review]

**Review by pombredanne — CHANGES_REQUESTED** [review]
Thank you ++ 
Do you mind to add a test with this?

**Comment by njv299** [comment]
@pombredanne I added a test as requested. 

Thanks!

**Review by pombredanne — APPROVED** [review]
LGTM. Thank you ++

**Comment by pombredanne** [comment]
Some of the tests on Circle and Appveyor take forever to complete.

**Comment by tardyp** [comment]
@pombredanne they don't.. they will never be done, because they are not done for PRs.
you should remove "continuous-integration/appveyor/branch" from the required tests in the protected branch area.
This test is only done *after* merge.

**Comment by pombredanne** [comment]
@tardyp thanks! You rock. I fixed this.

**Pull request merged**
