### PR TITLE
Add support for parsing complex license expressions

### PR DESCRIPTION
**Pull request by xavierfigueroav**
Make use of the [license-expression library](https://github.com/nexB/license-expression) to parse complex license expressions in SPDX documents.
Signed-off-by: Xavier Figueroa <xavierfigueroav@gmail.com>

### CODE REVIEW

**Comment by pombredanne** [comment]
@xavierfigueroav ping.... do you thing this could be rebased?

**Comment by xavierfigueroav** [comment]
> @xavierfigueroav ping.... do you thing this could be rebased?

Hi, PhiIippe :) I've rebased the code.

**Comment by pombredanne** [comment]
I am keeping this around as this will eventually be merged.

**Comment by armintaenzertng** [comment]
@pombredanne, is this still valid? Do you know when the "eventually" you managed might be?

As this PR is quite massive, it will cause a lot of conflicts in the future.

**Comment by armintaenzertng** [comment]
I'd like to see a rebase of this PR to get a better sense of what actually changed as the multiple merge commits make this rather incomprehensible.

@xavierfigueroav, are you willing to do this? Else I'll gladly take over from here :)

**Comment by nicoweidner** [comment]
Looking at the size, age and type of changes in this PR, I think the only viable course of action is to start from scratch based on current `main` and potentially use similar logic as in this PR (I didn't actually see the implementation details at first glance, since they are drowned in a sea of formatting changes...).

I will wait for a few days to see if anyone disagrees, then close this. The corresponding issue is https://github.com/spdx/tools-python/issues/10

**Comment by nicoweidner** [comment]
Closing this as announced earlier.

**Pull request closed without merging**
