### PR TITLE
Travis Build Fixed

### PR DESCRIPTION
**Pull request by yugeshk**
I'm not sure if this is the right fix - or if this is a proper fix at all, but from what I saw in the Travis logs, I guess this does the trick.

### CODE REVIEW

**Comment by yugeshk** [comment]
@pombredanne This patch fixes the other builds as well, not just Travis.

**Comment by sschuberth** [comment]
I just realized https://github.com/spdx/tools-python/pull/37 does almost the same. I tend to close this PR in favor of the other, as the other PR splits unrelated changes into different commits.

**Comment by yugeshk** [comment]
@sschuberth - will keep that in mind from next time. Sorry :sweat_smile:

**Comment by yugeshk** [comment]
However, I could make amend the PR to split it down, if thats the case.

**Pull request closed without merging**
