### PR TITLE
[WIP][Do not merge] Add relationships to python-tools

### LINKED ISSUE #138: Relationships not added (as per SPDX spec-2.1)
I've found that relationships are not added as per SPDX spec-v2.1. There was a GSoC project to update SPDX Python libraries, but I believe it didn't add relationships. Correct me if I've overlooked something or it was a decision from the mentors.

### PR DESCRIPTION
**Pull request by ShubhamKJha**
Signed-off-by: Shubham Kumar Jha <skjha832@gmail.com>

Fixes #138

### CODE REVIEW

**Comment by ShubhamKJha** [comment]
The errors doesn't look due to the changes I've made, instead it appears some dependencies are not supported in some Python versions.

**Comment by Yash-Varshney** [comment]
@ShubhamKJha I think you first need to create tests for the new file `relationship` that you have created, try checking on your local system by creating test. after that, you have to change the parsers code and make it compatible with all the formats. after that, adding the class to the examples and modifying the data will complete this issue.

**Comment by Yash-Varshney** [comment]
Also, @goneall @pombredanne can guide if I am right?

**Comment by goneall** [comment]
@pombredanne If you could verify the approach - I'm not as familiar with the Python tag/value parser

**Comment by ShubhamKJha** [comment]
@goneall it is currently in a very basic state, I would ask for a review once I'm ready. 
I just felt that the test-fails were not related to my changes here and hence I ran tests on the master of my fork. The tests are still failing. I'm looking into it, will give a better analysis when I find something.

**Comment by armintaenzertng** [comment]
As #138 is closed and no progress has been made here for over two years, I suggest to close this PR.

@ShubhamKJha, any objections?

**Comment by nicoweidner** [comment]
Closing this for now as relationships were added already. Please ping me or someone else if it should be reopened

**Pull request closed without merging**
