### PR TITLE
[experimentation] Try to disable appveyor

### PR DESCRIPTION
**Pull request by nicoweidner**
Just trying to see if I can fix/disable appveyor by modifying the config file

Signed-off-by: Nicolaus Weidner <nicolaus.weidner@tngtech.com>

### CODE REVIEW

**Comment by nicoweidner** [comment]
Didn't work :man_shrugging:

**Comment by pombredanne** [comment]
@nicoweidner my 2 cents: you should not disable windows testing, as this is used on windows.

**Comment by nicoweidner** [comment]
@pombredanne Completely agreed - this was intended as a temporary workaround. Currently, we are blocked from merging any new PR because the Appveyor tests hang for unknown reasons. Noone with access to Appveyor has come forth to check out what the issue is, and I cannot remove the `required` label from the check myself. The latest 4 PRs are stuck, and further PRs need to be rebased on those.

Do you have access to Appveyor, or alternatively can you make it an optional check for as long as it's broken?

**Comment by pombredanne** [comment]
@nicoweidner IMHO delete the appveyor file. And use GH workflows instead. I do not have access anymore to an admin to this repo.

**Pull request closed without merging**
