### PR TITLE
Misc. cleanups

### PR DESCRIPTION
**Pull request by sschuberth**
@pombredanne @ah450 @goneall Mind having a look?

### CODE REVIEW

**Comment by pombredanne** [comment]
@sschuberth I will for sure! I am travelling for the next couple days but I will come to it by the end of the week.

**Comment by pombredanne** [comment]
@sschuberth thanks ++ for this. with a quick glance it looks good and I will merge this in. :+1:

**Comment by pombredanne** [comment]
@neverpanic Thank you for chiming in. Mucho appreciated

**Comment by pombredanne** [comment]
@sschuberth I merged things alright in my fork here (with some extra cleanup on top) https://github.com/pombredanne/tools-python but I am having some issues with my push credentials at the Linux foundation master git repo.
Let me solve this and push to the master clone there soon.

**Comment by pombredanne** [comment]
@sschuberth I reviewed and merged (in a branch for now) here http://git.spdx.org/?p=spdx-tools-python.git;a=shortlog;h=refs/heads/code-cleanup
But somehow this takes forever to mirror which highly impractical. I will work things out so we setup the repo differently... or else we can use my fork and I will push now and then to the LF repo instead. 

@goneall using the LF git repo is a not a practical option IMHO for any shared workflow. We should instead have the mirror done the other way : the primary on Github and a cron mirror at the LF git.spdx.org

@neverpanic I see that you are working on welcomed improvements in your fork. Check out the changes I made on top of @sschuberth : they are extensive, but your changes should be easy to merge or rebase nonetheless. I can help with that when you fancy submitting a pull request.

**Comment by sschuberth** [comment]
> We should instead have the mirror done the other way : the primary on Github and a cron mirror at the LF git.spdx.org

I completely agree here. I has been very unpractical to contribute to spdx repos on GitHub in the past for me.

**Comment by pombredanne** [comment]
@sschuberth See https://github.com/bmwcarit/spdx-tools-python

**Comment by pombredanne** [comment]
@goneall @kestewart any reason why we could not set the main repo here rather than on the Git LF repo?
And mirror instead the GH repo at the LF?

**Comment by pombredanne** [comment]
@sschuberth the code I was referring is this branch: https://github.com/bmwcarit/spdx-tools-python/tree/improvements

**Comment by goneall** [comment]
@kestewart Can you check on this?  +1 for changing the mirror the other direction.  It is quite a bit of extra work for me to check the files in to the LF when the pull requests are coming in from github, but I have been able to work with it over the past year.

**Comment by pombredanne** [comment]
@sschuberth @neverpanic my branch was eventually synchronized from the LF git after a few days...
This https://github.com/spdx/tools-python/tree/code-cleanup contains both @sschuberth contributions and mine on top. I can submit a new PR for that or just let you review the changes there. If there is no objections I will merge in master later today (and we will wait for the mirroring from the LF back to github to occur ... eventually)

**Comment by sschuberth** [comment]
@pombredanne Yes, please file a PR, as that's more convenient to review.

**Comment by pombredanne** [comment]
@sschuberth done: see #5

**Pull request merged**
