### PR TITLE
Improvements to the README

### PR DESCRIPTION
**Pull request by sschuberth**
@pombredanne Not all links work for me yet. For example, I cannot access the AppVeyor build. Can you?

### CODE REVIEW

**Comment by pombredanne** [comment]
@sschuberth great!
I will religiously wait for all the CI runs to complete.

**Comment by pombredanne** [comment]
For https://ci.appveyor.com/project/spdx/tools-python/branch/master I get :
`Project not found or access denied.`

Could it be that you somehow also have some commercial creds on Appevyor and that you made the project "private"? or there may be an appeyor setting that determines the public/private status?

**Comment by sschuberth** [comment]
@pombredanne That's exactly what I meant by "Not all links work for me yet", and I wanted to know whether you have the same. Need to look into it...

**Comment by pombredanne** [comment]
as a side note, your use of the correct character lower/upper case mix for `macOS` would make any Apple marketing person proud of you :smile_cat: :green_apple: 
I am still in the past when it used to be [Mac OS X](http://web.archive.org/web/20040201232801/http://www.apple.com/macosx/)

**Comment by pombredanne** [comment]
About the `macOS` test failure, I use this function in my bash rc (on Linux) to create a clean virtualenv from scratch:
```
function venv {
 ARCHIVE=15.0.3.tar.gz
 mkdir -p tmp/venv
 wget -O tmp/venv.tgz https://github.com/pypa/virtualenv/archive/$ARCHIVE
 tar --strip-components=1 -xf tmp/venv.tgz -C tmp/venv
 python2 tmp/venv/virtualenv.py tmp
 . tmp/bin/activate
}
```

Alternatively we could add the scancode `configure` scripts here too. It works well and bring some sanity and help to have something clearly reproducible. This would help also as we could vendor in any deps (like I do in ScanCode proper for rdflib and others)

**Comment by sschuberth** [comment]
Looks like [getting AppVeyor to work with GitHub organizations](https://www.appveyor.com/docs/team-setup/#setting-up-appveyor-account-for-github-organization) is much more involving than for Travis CI or CircleCI, where is "just works". I'll give it a shot.

**Comment by pombredanne** [comment]
@sschuberth I could make you an SPDX org admin so you can use this superpower as needed :)
@goneall Any objections? I do vouch for @sschuberth  personally.

**Comment by pombredanne** [comment]
@sschuberth @goneall strike that last comment out. Sebastian already has the admin rights

**Comment by sschuberth** [comment]
@pombredanne Thanks, but I already *am* a GitHub SPDX org admin :-D

**Comment by sschuberth** [comment]
Phew, I finally managed to fix all CI integrations, @pombredanne!

**Comment by goneall** [comment]
No objections

 

Gary

**Pull request merged**
